version: '3.8'

services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: objectdetection-ldap
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin_password
      LDAP_ORGANISATION: "ObjectDetection"
      LDAP_DOMAIN: "objectdetection.com"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    networks:
      - app-network

  # Comment out the app service for now
  # app:
  #   build: .
  #   ...

volumes:
  ldap-data:
  ldap-config:

networks:
  app-network: