name: MSDTesting
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout v1
        uses: actions/checkout@v3
      - name: Run test
        run: make test
        working-directory: CS6015_SoftwareEngineering/Assignments/Project_1
